### PR TITLE
fix: deduplication of artifact and dependency references

### LINKED ISSUE #868: Inefficient deduplication logic and incorrect input handling for dependency resolution
### Description
The current artifact installation logic contains a flaw in how user inputs are processed before resolving dependencies.

### Current Behavior
The system performs a deduplication step on the input arguments provided by the user. However, this clean, deduplicated list of references is not correctly utilized as the starting point (seed) for the dependency resolution process.

### Problem:
Because the dependency resolver does not strictly use the deduplicated input set, the system fails to efficiently filter out redundant artifacts early in the process. This leads to inefficient execution and logical inconsistencies, as the resolution phase operates on a set of references that may not match the intended unique list derived from the inputs.

### Expected Behavior:
The flow should be strictly sequential:

1. Resolve and deduplicate all user inputs into a unique list of "resolved" references.
2. Pass only this unique list to the dependency resolver.
3. Ensure the resolver builds the dependency tree starting from these exact references to avoid redundancy and errors.

### PR DESCRIPTION
**Pull request by c2ndev**
**What type of PR is this?**

/kind bug

**Any specific area of the project related to this PR?**

/area cli

**What this PR does / why we need it**:
This PR fixes an incorrect behavior during the artifact installation phase.
During this step, `falcoctl` attempts to deduplicate artifact and dependency references to avoid multiple pulls from the container registry.
However, this deduplication currently does not work correctly.

**Which issue(s) this PR fixes**:

Fixes #868 

**Special notes for your reviewer**:

### CODE REVIEW

File: cmd/artifact/install/deps.go
Comment (leogr) [inline cmd/artifact/install/deps.go]: Before this changeset, this function took a single `artifactConfigResolver` and assumed it resolved references by calling `IndexCache.ResolveReference(ref)`.  Now we need to explicitly call `resolver` before inserting it in the map. 
This is correctly handled for primary deps (see line 173 below), but we are missing the `resolver` call here for alternative deps. 

Indeed, if we try to install `k8saudit-eks:0.2.1` together with `k8saudit-rules` (which, among alternatives, declares `k8saudit-eks:0.4.0`) we see the problem:
```
❯ ./falcoctl artifact install k8saudit-eks:0.2.1 k8saudit-rules
2025-12-23 14:01:21 INFO  Resolving dependencies ...
2025-12-23 14:01:24 ERROR unable to create new repository with ref k8saudit-eks:0.4.0: invalid reference: missing registry or repository
```

Before, the alternative dependency was correctly resolved:
```
❯ falcoctl artifact install k8saudit-eks:0.2.1 k8saudit-rules
2025-12-23 14:01:08 INFO  Resolving dependencies ...
2025-12-23 14:01:12 INFO  Installing artifacts refs: [k8saudit-eks:0.4.0 ghcr.io/falcosecurity/plugins/ruleset/k8saudit:latest json:0.7.0]
2025-12-23 14:01:12 INFO  Preparing to pull artifact ref: ghcr.io/falcosecurity/plugins/plugin/k8saudit-eks:0.4.0
...
```

Comment (cannarelladev) [reply cmd/artifact/install/deps.go]: the decoupling between "resolver" and pull of "configResolver" is intentional, in fact the goal is to avoid that inside the `ResolveDeps` the `inRefs` will be resolved again (they are already resolved). 
Anyway the described behavior about the alternative reference it's a bug. I'm fixing it resolving properly the ref before upserting the map.

File: cmd/artifact/install/install.go [hunk 1]
```diff
@@ -233,79 +234,37 @@ func (o *artifactInstallOptions) RunArtifactInstall(ctx context.Context, args []
...
+	signatures := make(map[string]*index.Signature)
 	for _, ref := range refs {
-		resolvedRef, err := o.IndexCache.ResolveReference(ref)
-		if err != nil {
-			return err
-		}
-
-		if signatures[resolvedRef] == nil {
+		if signatures[ref] == nil {
 			if sig := o.IndexCache.SignatureForIndexRef(ref); sig != nil {
```
[the remark this answers is not in the document]
Comment (cannarelladev) [reply cmd/artifact/install/install.go]: Fixed: the implementation now reuses an existing data structure to store all artifact names for `SignatureForIndexRef()`.
Additionally, the behavior of `falcoctl artifact install` when duplicate references are provided is not defined anywhere in the repository. Previously, this resulted in an error; now, duplicates are handled by selecting the highest version.

File: cmd/artifact/install/install_prepare_test.go [hunk 2]
```diff
@@ -0,0 +1,585 @@
...
+		foo150: {Name: "foo", Version: "1.5.0"},
+	}}
+
+	artifacts, err := o.prepareArtifactList(ctx, provider.ArtifactConfig, []string{
+		"foo:1.0.0",
+		"foo:2.0.0",
+		"foo:1.5.0",
+	})
+	assert.Len(t, artifacts, 1, "should keep only one version")
+	require.NoError(t, err)
```
Comment (leogr) [inline cmd/artifact/install/install_prepare_test.go]:
```suggestion
	require.NoError(t, err)
	assert.Len(t, artifacts, 1, "should keep only one version")
```
Nit. Shall the error stop the test immediately?

**Comment by c2ndev** [comment]
> > > Finally, I want only to reiterate on the fact that this PR introduces a behavioral change. For example, providing `foo:1.0.0 foo:2.0.0` produced an error before, now silently installs `2.0.0`. If possible, I would highlight this in the output logs during processing of deps and update the documentation (if any).
> > 
> > 
> > Thank you @leogr. How we would like to manage this change? In the Documentation is nowhere mentioned the previous behavior so we only need to understand if we would consider it as a breaking or not and mention it in the changelog. Meanwhile I'm highlighting it in the output logs
> 
> Since we don't have any documentation/changelog, we may add a line to the `falcoctl artifact install --help` usage message, if you agree. Otherwise just logging it would be enough atm, I guess.

OK, I agree! I will put it on the help message and as a log

**Review by leogr — APPROVED** [review]
